// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF0f9J5izNnNw5VbQ_J9HuMccaKXVSRuc',
    appId: '1:267198205592:web:710309c0843e0feda50aed',
    messagingSenderId: '267198205592',
    projectId: 'chuchu-a-jato',
    authDomain: 'chuchu-a-jato.firebaseapp.com',
    storageBucket: 'chuchu-a-jato.appspot.com',
    measurementId: 'G-Y3XDHVS9FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtrhqgzjszea7k4qrYHBJwrOSJ2w8AovE',
    appId: '1:267198205592:android:78b5ae3630aff529a50aed',
    messagingSenderId: '267198205592',
    projectId: 'chuchu-a-jato',
    storageBucket: 'chuchu-a-jato.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLkd6wOa_qMMPt2yHwwsJPhoGRY8nqwI',
    appId: '1:267198205592:ios:4a0b901cf5ee017aa50aed',
    messagingSenderId: '267198205592',
    projectId: 'chuchu-a-jato',
    storageBucket: 'chuchu-a-jato.appspot.com',
    iosBundleId: 'com.example.chuchuAJato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKLkd6wOa_qMMPt2yHwwsJPhoGRY8nqwI',
    appId: '1:267198205592:ios:90a160054779c77fa50aed',
    messagingSenderId: '267198205592',
    projectId: 'chuchu-a-jato',
    storageBucket: 'chuchu-a-jato.appspot.com',
    iosBundleId: 'com.example.chuchuAJato.RunnerTests',
  );
}
